adapter_name_or_path: ./saves/qwen_command_lora
bf16: true
cutoff_len: 512
dataset: latex_ds
dataset_dir: ./result_latex
do_train: true
eval_steps: 50
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 4
learning_rate: 0.0002
logging_steps: 5
lora_alpha: 32
lora_rank: 16
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: ../bhl/Models/Qwen2.5-1.5B-Instruct
num_train_epochs: 3.0
output_dir: ./saves/qwen_latex_lora
overwrite_cache: true
overwrite_output_dir: true
packing: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 4
save_steps: 100
stage: sft
template: qwen
trust_remote_code: true
val_size: 0.1
warmup_ratio: 0.1
