bf16: true
cutoff_len: 128
dataloader_num_workers: 0
dataloader_pin_memory: false
dataset: merged_ds
dataset_dir: result_com_lat
do_train: true
double_quantization: true
eval_steps: 25
eval_strategy: steps
finetuning_type: lora
flash_attn: sdpa
fp16: false
gradient_accumulation_steps: 16
gradient_checkpointing: true
ignore_data_skip: true
learning_rate: 0.00015
logging_first_step: true
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: ../bhl/Models/Qwen2.5-1.5B-Instruct
num_train_epochs: 5.0
output_dir: /home/michael/LLM/bhl_datasets/saves/qwen_com_lat_lora
overwrite_cache: true
overwrite_output_dir: true
packing: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 1
quantization_bit: 4
quantization_method: bitsandbytes
remove_unused_columns: true
report_to: none
save_safetensors: true
save_steps: 25
save_total_limit: 3
stage: sft
template: qwen
trust_remote_code: true
val_size: 0.05
warmup_ratio: 0.1
weight_decay: 0.01
